# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5dd5ffec3daacc2d15183b80846edcb35f215d156a3cfa275c34da93d3411d8ff8520cd1c2149011589f4e7a699831a201e7800c33444fd00607580132461e24

test:
  secret_key_base: 6c46f612158b8eeaf83e675b6331263447a4206048d0b52196e136a1abd6f0d64d6debfa2fc52ba97730f7ed22a4c16c2c865ea37bd13d20b3605d173785262b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
